# path or the data directory
# Here there must be chr in format chr{number}.annovar.vcf
samples: 'data'

# path to the results directory
outdir: 'results'

# path to the logs directory
logdir: 'logs'

# path to vep resources directory
vep_cache: 'cache'

# Chrs we wanna run
chr_list: ["chr1", "chr2", "chr3"]

parameters:
    paste_header:
        header_vcf: "resources/chr.header.txt"
    
    split_chr:
        num_lines: "30000"

    join_files:
        header_txt: "resources/txt.header.txt"

    annotate:
        # List of available anotations can be found in http://ftp.ensembl.org/pub/current_variation/indexed_vep_cache/
        # I guess that 'species', 'build', and 'release' are mandatory
        species: "homo_sapiens"
        build: "GRCh37"
        release: "104"
        # Listo of vep options is in: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html
        extra: "--everything --force_overwrite --af_gnomad --tab --per_gene --canonical --verbose"
        

resources:
    default:
        threads: 1
        mem:  4096
        walltime: 40

    remove_vcf_header:
        threads: 1
        mem:  12288
        walltime: 80
    
    split_chr:
        threads: 1
        mem:  4096
        walltime: 60

    annotate:
        threads: 8
        mem:  24576
        walltime: 120